name: Electron App Build and Upload Artifact

on:
  push:
    branches:
      - 'master'  # Trigger only on the 'master' branch
    paths:
      - 'package.json'  # Trigger when 'package.json' changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Get the previous commit's version from package.json
      - name: Get previous version from package.json
        id: prev_version
        run: |
          git fetch --depth=2
          prev_version=$(git show HEAD^:package.json | jq -r '.version')
          echo "Previous version: $prev_version"
          echo "prev_version=$prev_version" >> $GITHUB_ENV

      # Step 3: Get the current version from package.json
      - name: Get current version from package.json
        id: curr_version
        run: |
          current_version=$(jq -r '.version' package.json)
          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_ENV

      # Step 4: Check if the version has changed
      - name: Check if version has changed
        id: check_version
        run: |
          if [ "$prev_version" != "$current_version" ]; then
            echo "Version has changed, proceeding with build."
            echo "version_changed=true" >> $GITHUB_ENV
          else
            echo "Version has not changed, skipping build."
            echo "version_changed=false" >> $GITHUB_ENV

      # Step 5: Run the build only if the version has changed
      - name: Build app
        if: env.version_changed == 'true'
        run: npm run build -- --win --linux

      # Step 6: Upload build artifacts if version has changed
      - name: Upload build artifacts
        if: env.version_changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: electron-build-artifacts
          path: |
            dist/*.exe
            dist/*.AppImage