name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # Adjust to the branch where your source code lives

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version required by Docusaurus

      - name: Install dependencies
        working-directory: ./docs
        run: npm install

      - name: Build the site
        working-directory: ./docs
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
