name: Sign Electron App Artifacts

on:
  workflow_run:
    workflows: ["Electron App Build and Upload Artifact"]
    types:
      - completed

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code again
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download the uploaded artifact from the previous workflow
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: electron-build-artifacts

      # Step 3: Set up signing environment (Ensure that your signing key is in a secure vault)
      - name: Set up GPG (or any signing tool you use)
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SIGNING_PRIVATE_KEY }}

      # Step 4: Sign the artifacts (Using GPG or any other secure signing tool)
      - name: Sign the Windows executable
        run: gpg --armor --detach-sign --output dist/pomodazzle-1.0.1.exe.sig dist/pomodazzle-1.0.1.exe

      - name: Sign the Linux AppImage
        run: gpg --armor --detach-sign --output dist/pomodazzle-1.0.1.AppImage.sig dist/pomodazzle-1.0.1.AppImage

      # Step 5: Upload signed artifacts (optional, to be released later)
      - name: Upload signed artifacts
        uses: actions/upload-artifact@v3
        with:
          name: signed-electron-build-artifacts
          path: |
            dist/*.sig
